### ISSUE TITLE
Plugin throws an exception in IntelliJ products running with JDK 1.6

### ISSUE THREAD

**Issue by akutarba** [vermut/intellij-ansible#1]
IntelliJ IDEA 14.1.3, RubyMine 7.1.2
To reproduce install plugin into IDE which is running under JDK 1.6, get an exception on the start:

cz/juzna/intellij/neon/reference/AnsibleReferenceContributor : Unsupported major.minor version 52.0 [Plugin: YAML/Ansible support]
com.intellij.diagnostic.PluginException: cz/juzna/intellij/neon/reference/AnsibleReferenceContributor : Unsupported major.minor version 52.0 [Plugin: YAML/Ansible support]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
	at com.intellij.psi.impl.source.resolve.reference.PsiReferenceContributorEP.access$000(PsiReferenceContributorEP.java:30)
	at com.intellij.psi.impl.source.resolve.reference.PsiReferenceContributorEP$1.compute(PsiReferenceContributorEP.java:43)
	at com.intellij.psi.impl.source.resolve.reference.PsiReferenceContributorEP$1.compute(PsiReferenceContributorEP.java:38)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
	at com.intellij.psi.impl.source.resolve.reference.PsiReferenceContributorEP.getInstance(PsiReferenceContributorEP.java:54)
	at com.intellij.psi.impl.source.resolve.reference.PsiReferenceContributorEP.getInstance(PsiReferenceContributorEP.java:30)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:154)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:127)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:115)
	at com.intellij.lang.LanguageExtension.allForLanguage(LanguageExtension.java:71)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl$2.create(ReferenceProvidersRegistryImpl.java:49)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl$2.create(ReferenceProvidersRegistryImpl.java:45)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:56)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getRegistrar(ReferenceProvidersRegistryImpl.java:86)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:96)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:70)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:56)
	at org.jetbrains.yaml.psi.impl.YAMLKeyValueImpl.getReferences(YAMLKeyValueImpl.java:137)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.addReferences(SharedPsiElementImplUtil.java:67)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:49)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:63)
	at com.intellij.psi.impl.PsiElementBase.findReferenceAt(PsiElementBase.java:87)
	at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:418)
	at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:390)
	at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:616)
	at com.intellij.codeInsight.TargetElementUtilBase.findReference(TargetElementUtilBase.java:117)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:319)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:201)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
Caused by: java.lang.UnsupportedClassVersionError: cz/juzna/intellij/neon/reference/AnsibleReferenceContributor : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
	... 52 more

**Comment by vermut** [comment]
I'll try to compile version for 1.6.

Just curious - how and why are you running IDE under JDK 1.6?

**Comment by vermut** [comment]
Try a0ffd9304d342cb7b2f99103035eb87fb7bc561f/.idea/intellij-ansible.zip

**Comment by akutarba** [comment]
Verified that fixed with the latest version of plugin. Thanks:)

>Just curious - how and why are you running IDE under JDK 1.6?

Almost all major issues with JDK 1.8 are fixed, but we still recommend to use IDE with the JDK 1.6 (this fix will be actual for them) or with bundled JDK8.
