### ISSUE TITLE
Don't works with RubyMine 7.1

### ISSUE THREAD

**Issue by rhapsodyv** [vermut/intellij-ansible#15]
Hi,

Using RubyMine 7.1 OS X and I'm getting this exception:
```java
org.jetbrains.yaml.psi.impl.YAMLFileImpl cannot be cast to cz.juzna.intellij.neon.psi.NeonFile
java.lang.ClassCastException: org.jetbrains.yaml.psi.impl.YAMLFileImpl cannot be cast to cz.juzna.intellij.neon.psi.NeonFile
	at cz.juzna.intellij.neon.reference.AnsibleUtil.searchKeyPairs(AnsibleUtil.java:98)
	at cz.juzna.intellij.neon.reference.AnsibleUtil.findNames(AnsibleUtil.java:58)
	at cz.juzna.intellij.neon.reference.AnsibleNamesContributor.getNames(AnsibleNamesContributor.java:23)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:116)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:97)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:31)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)



java.lang.ClassCastException: org.jetbrains.yaml.psi.impl.YAMLFileImpl cannot be cast to cz.juzna.intellij.neon.psi.NeonFile
	at cz.juzna.intellij.neon.reference.AnsibleUtil.searchKeyPairs(AnsibleUtil.java:98)
	at cz.juzna.intellij.neon.reference.AnsibleUtil.findNames(AnsibleUtil.java:58)
	at cz.juzna.intellij.neon.reference.AnsibleNamesContributor.getNames(AnsibleNamesContributor.java:23)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:116)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:97)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:31)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)



java.lang.ClassCastException: org.jetbrains.yaml.psi.impl.YAMLFileImpl cannot be cast to cz.juzna.intellij.neon.psi.NeonFile
	at cz.juzna.intellij.neon.reference.AnsibleUtil.searchKeyPairs(AnsibleUtil.java:98)
	at cz.juzna.intellij.neon.reference.AnsibleUtil.findAllProperties(AnsibleUtil.java:44)
	at cz.juzna.intellij.neon.reference.AnsiblePropertiesContributor.getNames(AnsiblePropertiesContributor.java:22)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:116)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:97)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:31)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)


```

**Comment by vermut** [comment]
What edition? Feels like you have native YAML support enabled there.

**Comment by rhapsodyv** [comment]
Yeah. I updated and this exception is gone.

How do I disable the native YAML support and fully use intellij-ansible?

I'm using rubymine 7.1

Thanks.

**Comment by vermut** [comment]
Updated RubyMine or plugin? To what version?

**Comment by vermut** [comment]
Feels like the same issue as #14 - conflict with existing YAML

**Comment by vermut** [comment]
Try 0.8.0
