### ISSUE TITLE
Error while indexing: Could not match input

### ISSUE THREAD

**Issue by Janmm14** [vermut/intellij-ansible#17]
Error while indexing C:\Users\*\.m2\repository\\\*\\\*\\\*\\\*\\\*-3.2.0.2-SNAPSHOT.jar!\*\\de_AT.lng.yml
To reindex this file IDEA has to be restarted: cz.juzna.intellij.neon.lexer._NeonLexer: Error: could not match input

Error:
```
java.lang.Error: cz.juzna.intellij.neon.lexer._NeonLexer: Error: could not match input
	at cz.juzna.intellij.neon.lexer._NeonLexer.zzScanError(_NeonLexer.java:525)
	at cz.juzna.intellij.neon.lexer._NeonLexer.advance(_NeonLexer.java:838)
	at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
	at com.intellij.lexer.FlexAdapter.getTokenType(FlexAdapter.java:58)
	at com.intellij.lexer.MergingLexerAdapterBase.locateToken(MergingLexerAdapterBase.java:71)
	at com.intellij.lexer.MergingLexerAdapterBase.getTokenType(MergingLexerAdapterBase.java:46)
	at com.intellij.lang.cacheBuilder.DefaultWordsScanner.processWords(DefaultWordsScanner.java:74)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:119)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:106)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:85)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:79)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:397)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1743)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1675)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1623)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:101)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:97)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:290)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:310)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:304)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

File contents:
```
#* language file: de_AT
#Author: *
#ESCAPE Special chars: &uuml; &auml; &ouml; &szlig;
#& == PARAGRAPH (color codes)
info:
  short: 'de_AT'
  author: '*'
  long: 'Deutsch (&Ouml;sterreich)'
  en_name: 'German (Austria)'
  plugin: '*'
lang:
  XYC-name: 'XYC'
  XYC-prefix: '&7[&8XYC&7] '
  XYC-pricol: '&7'
  XYC-warningcol: '&8'
  XYC-codecol: '&3'
  XYC-kickconsolemsg: '%1$sDas Kommando /%2$s kann nur von einem Spieler ausgef&uuml;hrt werden!'
  XYC-noperms-1: '&7Du hast keine Berechtigung, um den Befehl %1$s zu verwenden.'
  XYC-noperms-2: '&7Ben&ouml;tigte Berechtigung: &3%1$s'
  XYC-nopermsact-1: '&7Du hast keine Berechtigung, um folgende Aktion auszuf&uuml;hren: &3%1$s'
  XYC-lang-nan: '&8Fehler beim Aufrufen der Hilfe: Die Seitenzahl ist keine Zahl!'
  XYC-lang-header: '&7==={&l&8%1$s - Seite %2$s/%3$s&r&7}&7==='
  XYC-lang-nextpage: '&8Um die n&auml;chste Seite zu sehen, tippe &3/%1$s %2$s&8.' 
```

(Censored with ```*```)

**Edit:** IntelliJ IDEA 14.1.3 CE and plugin version 0.7.2

**Comment by vermut** [comment]
Try version 0.7.3?

**Comment by Janmm14** [comment]
Will do soon

**Comment by vermut** [comment]
I made a different Yaml parser plugin. It does not include any Ansible functionality but parses YAML really good. Can you [try it](https://github.com/vermut/intellij-snakeyaml/raw/master/intellij-snakeyaml.zip) and see if it works better?
