### ISSUE TITLE
org.jetbrains.yaml.psi.impl.YAMLFileImpl cannot be cast to cz.juzna.intellij.neon.psi.NeonFile

### ISSUE THREAD

**Issue by zbigniewpekala** [vermut/intellij-ansible#18]
I installed plugin from https://plugins.jetbrains.com/plugin/7792?pr=idea, then pressed CMD+N to search for files and it crashed. I'm working on newest OSX with latest version of PyCharm.

```
org.jetbrains.yaml.psi.impl.YAMLFileImpl cannot be cast to cz.juzna.intellij.neon.psi.NeonFile
java.lang.ClassCastException: org.jetbrains.yaml.psi.impl.YAMLFileImpl cannot be cast to cz.juzna.intellij.neon.psi.NeonFile
	at cz.juzna.intellij.neon.reference.AnsibleUtil.searchKeyPairs(AnsibleUtil.java:98)
	at cz.juzna.intellij.neon.reference.AnsibleUtil.findNames(AnsibleUtil.java:58)
	at cz.juzna.intellij.neon.reference.AnsibleNamesContributor.getNames(AnsibleNamesContributor.java:23)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:116)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:97)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:31)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

This is 100% reproducable.

**Comment by vermut** [comment]
Duplicate #15
