### ISSUE TITLE
Crash indexing .yml files

### ISSUE THREAD

**Issue by jkleint** [vermut/intellij-ansible#2]
IDEA 14.1.3
JRE 1.8.0_45
```
Error while indexing file.yml
To reindex this file IDEA has to be restarted: cz.juzna.intellij.neon.lexer._NeonLexer: Error: could not match input
java.lang.Error: cz.juzna.intellij.neon.lexer._NeonLexer: Error: could not match input
	at cz.juzna.intellij.neon.lexer._NeonLexer.zzScanError(_NeonLexer.java:518)
	at cz.juzna.intellij.neon.lexer._NeonLexer.advance(_NeonLexer.java:831)
	at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
	at com.intellij.lexer.FlexAdapter.getTokenStart(FlexAdapter.java:64)
	at com.intellij.lexer.DelegateLexer.getTokenStart(DelegateLexer.java:55)
	at com.intellij.lexer.MergingLexerAdapterBase.getTokenEnd(MergingLexerAdapterBase.java:59)
	at com.intellij.lang.cacheBuilder.DefaultWordsScanner.processWords(DefaultWordsScanner.java:78)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:119)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:106)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:85)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:79)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:397)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1743)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1675)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1623)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:101)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:97)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:290)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:310)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:304)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by vermut** [comment]
Please attach file.yml

**Comment by azumafuji** [comment]
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
IntelliJ 14.1.3  Build IU-141.1010.3

I also got the same error.  Yaml content from file is included below.

```
Error while indexing /Volumes/Mugen/src/trialreach/infrastructure/roles/webservers/tasks/install_frontend_tools.yml
To reindex this file IDEA has to be restarted: cz.juzna.intellij.neon.lexer._NeonLexer: Error: could not match input
java.lang.Error: cz.juzna.intellij.neon.lexer._NeonLexer: Error: could not match input
	at cz.juzna.intellij.neon.lexer._NeonLexer.zzScanError(_NeonLexer.java:518)
	at cz.juzna.intellij.neon.lexer._NeonLexer.advance(_NeonLexer.java:831)
	at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
	at com.intellij.lexer.FlexAdapter.getTokenStart(FlexAdapter.java:64)
	at com.intellij.lexer.DelegateLexer.getTokenStart(DelegateLexer.java:55)
	at com.intellij.lexer.MergingLexerAdapterBase.getTokenEnd(MergingLexerAdapterBase.java:59)
	at com.intellij.lang.cacheBuilder.DefaultWordsScanner.processWords(DefaultWordsScanner.java:86)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:119)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:106)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:85)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:79)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:397)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1743)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1675)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1623)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:101)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:97)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:290)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:310)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:304)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

```yaml
---
- name: add ppa for nodejs
  action: apt_repository repo='ppa:chris-lea/node.js' update_cache=yes

- name: ensure packages are installed
  action: apt pkg={{ item }}
  with_items:
      - nodejs
      - ruby
      - rubygems

- name: install gems for asset compilation
  gem: name={{ item }} state=present user_install=no
  with_items:
      - sass
      - compass

- name: install grunt for asset compilation
  npm: name=grunt-cli version=0.1.13 global=yes state=present

- name: install bower for asset dependencies
  npm: name=bower version=1.3.9 global=yes state=present

```

**Comment by vermut** [comment]
It parses fine with me, version 0.7, Java 1.8.0_40. But I doubt this minor version breaks things.

Maybe you have some unusual whitespace chars there? Can you zip the file and attach it?

**Comment by azumafuji** [comment]
There are no unusual whitespace characters.  It seems that every time I re-open IDEA, I get the same error on a different file. I'm opening a large project (Ansible based) with many YAML files and I cannot post the other files here. I've double checked whitespace and formatting and the files validate in IDEA and using all the available YAML validators I could find.

**Comment by azumafuji** [comment]
I've attached the file that caused the initial error.

**Comment by vermut** [comment]
Seems like attach not working like this. Ok, maybe you can give me more details about the project? How many files? What are the file structure? What type of project?

**Comment by azumafuji** [comment]
There are about 85 YAML files and they are distributed in folders following the Ansible [recommended folder structure](http://docs.ansible.com/playbooks_best_practices.html#directory-layout).  The project is our automated provisioning project so it's all Ansible configuration files and a few Python scripts.

**Comment by jakirkham** [comment]
First off, thanks for writing this plugin. It is awesome!

Also, have seen this problem. Only happens with one of the many YAML files in my projects. Never ends up being the same YAML file (if I close and reopen PyCharm). Here is one file it complained about. Of course, it ended up actually parsing the file fine in the same session that it raised the exception in. It seems that when it complains about a file that file was not opened in a tab already.

    fws:
    - created_on: '2013-03-22T06:43:43.879697'
      fw_id: 2
      spec:
        _priority: 1
        _tasks:
        - _fw_name: ScriptTask
          script: echo "Task B-2"
    - created_on: '2013-03-22T06:43:43.879540'
      fw_id: 1
      spec:
        _priority: 1
        _tasks:
        - _fw_name: ScriptTask
          script: echo "Task B-1"
    links:
      1:
      - 2
    metadata: {}

**Comment by vermut** [comment]
Feels like it's findUsagesProvider. It's the only place where DefaultWordsScanner is used. I removed it for now, please test 0.7.3

**Comment by memelet** [comment]
I tried 0.7.3. Idea no longer crashes, but no ansible files are marked as ansible files and no yaml parsing happens at all.

**Comment by jakirkham** [comment]
Was using this on PyCharm. So, will check once an update appears.
