### ISSUE TITLE
[error] null item from contributor ...AnsibleNamesContributor...

### ISSUE THREAD

**Issue by fzzr-** [vermut/intellij-ansible#22]
Intellij Idea 14.1.4 CE

log:
```log
null item from contributor cz.juzna.intellij.neon.reference.AnsibleNamesContributor@7c0b5c05 for name ?? complex value ?? [Plugin: YAML/Ansible support]
com.intellij.diagnostic.PluginException: null item from contributor cz.juzna.intellij.neon.reference.AnsibleNamesContributor@7c0b5c05 for name ?? complex value ?? [Plugin: YAML/Ansible support]
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$3.process(ContributorsBasedGotoByModel.java:227)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$3.process(ContributorsBasedGotoByModel.java:195)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by vermut** [comment]
When?

**Comment by fzzr-** [comment]
I don't know when. Sorry.

Заметил в логе, счёл нужным уведомить автора плагина.
