### ISSUE TITLE
java.lang.StackOverflowError in plugin

### ISSUE THREAD

**Issue by sshnaidm** [vermut/intellij-ansible#41]
Using plugin I've got exceptions:
(the yamls are from project: https://github.com/redhat-openstack/khaleesi )
Idea 15.0.4 Build 143.2287
Plugin version: 0.9.2

null
java.lang.StackOverflowError
	at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseScalar(NeonParser.java:120)
	at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseScalar(NeonParser.java:181)
	at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseScalar(NeonParser.java:181)
	at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseScalar(NeonParser.java:181)
	at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseScalar(NeonParser.java:181)
	at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseScalar(NeonParser.java:181)
...

**Comment by vermut** [comment]
Cannot repeat. Can you catch what file is that?

**Comment by JustinHead** [comment]
I can trigger this when writing the following in a meta/main.yml:

```yaml
---
dependencies:
  - role: foo
    when: "foo == 'bar'"
```
