### ISSUE TITLE
NullPointerException occurred at unknown time/operation

### ISSUE THREAD

**Issue by myniva** [vermut/intellij-ansible#47]
I can't really say why or when this exception occurred by I thought it might be helpful for you.

```
java.lang.NullPointerException
    at lv.kid.vermut.intellij.yaml.reference.AnsibleUtil.findFiles(AnsibleUtil.java:84)
    at lv.kid.vermut.intellij.yaml.reference.AnsibleUtil.findRoleNames(AnsibleUtil.java:31)
    at lv.kid.vermut.intellij.yaml.reference.AnsibleNamesContributor.getNames(AnsibleNamesContributor.java:26)
    at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:116)
    at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$2.processInReadAction(ContributorsBasedGotoByModel.java:97)
    at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:31)
    at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:28)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:962)
    at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
    at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:128)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by robertwatson3** [comment]
I'm seeing this error a ton.

> 2:38:39 PM NullPointerException: null
2:38:43 PM NullPointerException: null
2:38:47 PM NullPointerException: null
2:39:47 PM NullPointerException: null
2:39:50 PM NullPointerException: null
2:40:41 PM NullPointerException: null
2:43:41 PM NullPointerException: null
2:43:45 PM NullPointerException: null
2:43:46 PM NullPointerException: null
2:44:05 PM NullPointerException: null
2:46:30 PM NullPointerException: null
2:46:34 PM NullPointerException: null
2:53:20 PM NullPointerException: null
3:49:06 PM NullPointerException: null
3:49:08 PM NullPointerException: null
3:50:22 PM NullPointerException: null
3:58:17 PM NullPointerException: null
3:58:22 PM NullPointerException: null
3:58:51 PM NullPointerException: null
3:58:53 PM NullPointerException: null
3:58:58 PM NullPointerException: null
3:58:59 PM NullPointerException: null
3:59:02 PM NullPointerException: null
3:59:06 PM NullPointerException: null
3:59:08 PM NullPointerException: null
3:59:15 PM NullPointerException: null
3:59:16 PM NullPointerException: null
4:08:14 PM NullPointerException: null

**Comment by vermut** [comment]
I can add _ignore_ style exception handling here so this code won't annoy you, but it's better if you provide me a sample project where this bug manifests.
