### ISSUE TITLE
java.lang.StackOverflowError on large yaml imput

### ISSUE THREAD

**Issue by rasselin** [vermut/intellij-ansible#51]
When using this large (13000+ line) opensource yaml file, getting a StackOverflowError and generallyslow performance.

http://git.openstack.org/cgit/openstack-infra/project-config/tree/zuul/layout.yaml

```
null
java.lang.StackOverflowError
    at java.util.regex.Pattern$Slice.match(Pattern.java:3870)
    at java.util.regex.Pattern$Start.match(Pattern.java:3408)
    at java.util.regex.Matcher.search(Matcher.java:1199)
    at java.util.regex.Matcher.find(Matcher.java:592)
    at java.util.regex.Matcher.replaceAll(Matcher.java:902)
    at java.lang.String.replace(String.java:2180)
    at lv.kid.vermut.intellij.yaml.parser.NeonParser.validateTabsSpaces(NeonParser.java:288)
    at lv.kid.vermut.intellij.yaml.parser.NeonParser.advanceLexer(NeonParser.java:252)
    at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseArray(NeonParser.java:184)
    at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseValue(NeonParser.java:65)
    at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseArray(NeonParser.java:171)
    at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseValue(NeonParser.java:65)
    at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseArray(NeonParser.java:171)
    at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseValue(NeonParser.java:65)
    at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseArray(NeonParser.java:171)
    at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseValue(NeonParser.java:65)
    at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseArray(NeonParser.java:171)
    at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseValue(NeonParser.java:65)
    at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseArray(NeonParser.java:171)
    at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseValue(NeonParser.java:65)
...
```

**Comment by vermut** [comment]
Yes. Ansible parser is rather simple. It doesn't expect 13k line full yaml syntax playbooks. Can you try sister project SnakeYAML? Maybe it will be able to digest your data
