### ISSUE TITLE
Crash when editing "Code style" in PyCharm: "TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.getFileType must not return null"

### ISSUE THREAD

**Issue by Bahus** [vermut/intellij-ansible#6]
OS: Ubuntu 14.04.2

Hello, plugin was installed from PyCharm 4.5.1.1245, when I click on File -> Settings -> Editor -> Code Style -> YAML/Ansible, mouser cursor switches to "busy" state and IDE reports about plugin crash:
```
@NotNull method com/intellij/application/options/TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.getFileType must not return null
java.lang.IllegalStateException: @NotNull method com/intellij/application/options/TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.getFileType must not return null
	at com.intellij.application.options.TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.getFileType(TabbedLanguageCodeStylePanel.java:588)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.createHighlighter(TabbedLanguageCodeStylePanel.java:580)
	at com.intellij.application.options.CodeStyleAbstractPanel.a(CodeStyleAbstractPanel.java:377)
	at com.intellij.application.options.CodeStyleAbstractPanel.updatePreview(CodeStyleAbstractPanel.java:171)
	at com.intellij.application.options.CodeStyleAbstractPanel.<init>(CodeStyleAbstractPanel.java:117)
	at com.intellij.application.options.CodeStyleAbstractPanel.<init>(CodeStyleAbstractPanel.java:94)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.<init>(TabbedLanguageCodeStylePanel.java:556)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.addIndentOptionsTab(TabbedLanguageCodeStylePanel.java:104)
	at cz.juzna.intellij.neon.editor.NeonCodeStyleSettingsProvider$1$1.initTabs(NeonCodeStyleSettingsProvider.java:25)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.f(TabbedLanguageCodeStylePanel.java:140)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.getPreviewText(TabbedLanguageCodeStylePanel.java:217)
	at com.intellij.application.options.CodeStyleAbstractPanel.b(CodeStyleAbstractPanel.java:148)
	at com.intellij.application.options.CodeStyleAbstractPanel.<init>(CodeStyleAbstractPanel.java:105)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.<init>(TabbedLanguageCodeStylePanel.java:68)
	at cz.juzna.intellij.neon.editor.NeonCodeStyleSettingsProvider$1$1.<init>(NeonCodeStyleSettingsProvider.java:22)
	at cz.juzna.intellij.neon.editor.NeonCodeStyleSettingsProvider$1.createPanel(NeonCodeStyleSettingsProvider.java:22)
	at com.intellij.application.options.CodeStyleAbstractConfigurable.createComponent(CodeStyleAbstractConfigurable.java:49)
	at com.intellij.application.options.codeStyle.NewCodeStyleSettingsPanel.<init>(NewCodeStyleSettingsPanel.java:45)
	at com.intellij.application.options.CodeStyleSchemesConfigurable$2.createPanel(CodeStyleSchemesConfigurable.java:232)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel.a(CodeStyleMainPanel.java:223)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel.d(CodeStyleMainPanel.java:217)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel.access$000(CodeStyleMainPanel.java:43)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel$3.run(CodeStyleMainPanel.java:146)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
	at java.awt.Dialog.show(Dialog.java:1082)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:114)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:593)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:644)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:483)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

```

**Comment by mcapanema** [comment]
It happens on RubyMine too.

RubyMine 7.1.4  Build #RM-141.1835
JDK: 1.6.0_65
VM: Java HotSpot(TM) 64-Bit Server VM
Vendor: Apple Inc.
OS: Mac OS X
Last Action: EditorDown

***idea.log***:
```
2015-09-17 23:09:46,445 [ 487188]   WARN - options.ex.ConfigurableWrapper - XML does not provide id for class org.jetbrains.plugins.ruby.settings.RubyModuleStructureConfigurable
2015-09-17 23:09:46,458 [ 487201]   WARN - options.ex.ConfigurableWrapper - XML does not provide id for class org.jetbrains.plugins.ruby.settings.RubyActiveModuleSdkConfigurable
2015-09-17 23:09:52,499 [ 493242]  ERROR - llij.ide.plugins.PluginManager - @NotNull method com/intellij/application/options/TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.getFileType must not return null
java.lang.IllegalStateException: @NotNull method com/intellij/application/options/TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.getFileType must not return null
	at com.intellij.application.options.TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.getFileType(TabbedLanguageCodeStylePanel.java:588)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.createHighlighter(TabbedLanguageCodeStylePanel.java:580)
	at com.intellij.application.options.CodeStyleAbstractPanel.a(CodeStyleAbstractPanel.java:377)
	at com.intellij.application.options.CodeStyleAbstractPanel.updatePreview(CodeStyleAbstractPanel.java:171)
	at com.intellij.application.options.CodeStyleAbstractPanel.<init>(CodeStyleAbstractPanel.java:117)
	at com.intellij.application.options.CodeStyleAbstractPanel.<init>(CodeStyleAbstractPanel.java:94)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.<init>(TabbedLanguageCodeStylePanel.java:556)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.addIndentOptionsTab(TabbedLanguageCodeStylePanel.java:104)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.initTabs(TabbedLanguageCodeStylePanel.java:86)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.f(TabbedLanguageCodeStylePanel.java:140)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.getPreviewText(TabbedLanguageCodeStylePanel.java:217)
	at com.intellij.application.options.CodeStyleAbstractPanel.b(CodeStyleAbstractPanel.java:148)
	at com.intellij.application.options.CodeStyleAbstractPanel.<init>(CodeStyleAbstractPanel.java:105)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.<init>(TabbedLanguageCodeStylePanel.java:68)
	at cz.juzna.intellij.neon.editor.NeonCodeStyleSettingsProvider$SimpleCodeStyleMainPanel.<init>(NeonCodeStyleSettingsProvider.java:42)
	at cz.juzna.intellij.neon.editor.NeonCodeStyleSettingsProvider$1.createPanel(NeonCodeStyleSettingsProvider.java:35)
	at com.intellij.application.options.CodeStyleAbstractConfigurable.createComponent(CodeStyleAbstractConfigurable.java:49)
	at com.intellij.application.options.codeStyle.NewCodeStyleSettingsPanel.<init>(NewCodeStyleSettingsPanel.java:45)
	at com.intellij.application.options.CodeStyleSchemesConfigurable$2.createPanel(CodeStyleSchemesConfigurable.java:232)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel.a(CodeStyleMainPanel.java:223)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel.d(CodeStyleMainPanel.java:217)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel.access$000(CodeStyleMainPanel.java:43)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel$3.run(CodeStyleMainPanel.java:146)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:205)
	at java.awt.Dialog$1.run(Dialog.java:1049)
	at java.awt.Dialog$3.run(Dialog.java:1101)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Dialog.show(Dialog.java:1099)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:114)
	at com.intellij.ide.MacOSApplicationProvider$Worker$1.handlePreferences(MacOSApplicationProvider.java:99)
	at com.apple.eawt._AppEventLegacyHandler$2.dispatchEvent(_AppEventLegacyHandler.java:90)
	at com.apple.eawt._AppEventLegacyHandler.sendEventToEachListenerUntilHandled(_AppEventLegacyHandler.java:168)
	at com.apple.eawt._AppEventLegacyHandler.handlePreferences(_AppEventLegacyHandler.java:88)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:253)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:244)
	at com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:489)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2015-09-17 23:09:52,500 [ 493243]  ERROR - llij.ide.plugins.PluginManager - RubyMine 7.1.4  Build #RM-141.1835
2015-09-17 23:09:52,500 [ 493243]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.6.0_65
2015-09-17 23:09:52,500 [ 493243]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM
2015-09-17 23:09:52,500 [ 493243]  ERROR - llij.ide.plugins.PluginManager - Vendor: Apple Inc.
2015-09-17 23:09:52,500 [ 493243]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X
2015-09-17 23:09:52,500 [ 493243]  ERROR - llij.ide.plugins.PluginManager - Last Action: EditorDown
```

***RubyMine Exception***:
```
@NotNull method com/intellij/application/options/TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.getFileType must not return null
java.lang.IllegalStateException: @NotNull method com/intellij/application/options/TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.getFileType must not return null
	at com.intellij.application.options.TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.getFileType(TabbedLanguageCodeStylePanel.java:588)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.createHighlighter(TabbedLanguageCodeStylePanel.java:580)
	at com.intellij.application.options.CodeStyleAbstractPanel.a(CodeStyleAbstractPanel.java:377)
	at com.intellij.application.options.CodeStyleAbstractPanel.updatePreview(CodeStyleAbstractPanel.java:171)
	at com.intellij.application.options.CodeStyleAbstractPanel.<init>(CodeStyleAbstractPanel.java:117)
	at com.intellij.application.options.CodeStyleAbstractPanel.<init>(CodeStyleAbstractPanel.java:94)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.<init>(TabbedLanguageCodeStylePanel.java:556)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.addIndentOptionsTab(TabbedLanguageCodeStylePanel.java:104)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.initTabs(TabbedLanguageCodeStylePanel.java:86)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.f(TabbedLanguageCodeStylePanel.java:140)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.getPreviewText(TabbedLanguageCodeStylePanel.java:217)
	at com.intellij.application.options.CodeStyleAbstractPanel.b(CodeStyleAbstractPanel.java:148)
	at com.intellij.application.options.CodeStyleAbstractPanel.<init>(CodeStyleAbstractPanel.java:105)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.<init>(TabbedLanguageCodeStylePanel.java:68)
	at cz.juzna.intellij.neon.editor.NeonCodeStyleSettingsProvider$SimpleCodeStyleMainPanel.<init>(NeonCodeStyleSettingsProvider.java:42)
	at cz.juzna.intellij.neon.editor.NeonCodeStyleSettingsProvider$1.createPanel(NeonCodeStyleSettingsProvider.java:35)
	at com.intellij.application.options.CodeStyleAbstractConfigurable.createComponent(CodeStyleAbstractConfigurable.java:49)
	at com.intellij.application.options.codeStyle.NewCodeStyleSettingsPanel.<init>(NewCodeStyleSettingsPanel.java:45)
	at com.intellij.application.options.CodeStyleSchemesConfigurable$2.createPanel(CodeStyleSchemesConfigurable.java:232)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel.a(CodeStyleMainPanel.java:223)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel.d(CodeStyleMainPanel.java:217)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel.access$000(CodeStyleMainPanel.java:43)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel$3.run(CodeStyleMainPanel.java:146)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:205)
	at java.awt.Dialog$1.run(Dialog.java:1049)
	at java.awt.Dialog$3.run(Dialog.java:1101)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Dialog.show(Dialog.java:1099)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:114)
	at com.intellij.ide.MacOSApplicationProvider$Worker$1.handlePreferences(MacOSApplicationProvider.java:99)
	at com.apple.eawt._AppEventLegacyHandler$2.dispatchEvent(_AppEventLegacyHandler.java:90)
	at com.apple.eawt._AppEventLegacyHandler.sendEventToEachListenerUntilHandled(_AppEventLegacyHandler.java:168)
	at com.apple.eawt._AppEventLegacyHandler.handlePreferences(_AppEventLegacyHandler.java:88)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:253)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:244)
	at com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:489)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```
