### ISSUE TITLE
Assertion failed: Network shouldn't be accessed in EDT or inside read action

### ISSUE THREAD

**Issue by drichelson** [vermut/intellij-ansible#65]
As reported by:
IntelliJ IDEA 2016.3
Build #IU-163.7743.44, built on November 17, 2016
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

```Assertion failed: Network shouldn't be accessed in EDT or inside read action
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:379)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:251)
	at lv.kid.vermut.intellij.yaml.reference.AnsibleVariableValuesDocumentationProvider.getQuickNavigateInfo(AnsibleVariableValuesDocumentationProvider.java:45)
	at lv.kid.vermut.intellij.yaml.reference.AnsibleVariableValuesDocumentationProvider.generateDoc(AnsibleVariableValuesDocumentationProvider.java:61)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:144)
	at com.intellij.codeInsight.documentation.DocumentationManager$DefaultDocumentationCollector.a(DocumentationManager.java:1149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:80)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:135)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:80)
	at com.intellij.codeInsight.documentation.QuickDocUtil.runInReadActionWithWriteActionPriorityWithRetries(QuickDocUtil.java:96)
	at com.intellij.codeInsight.documentation.DocumentationManager$DefaultDocumentationCollector.getDocumentation(DocumentationManager.java:1147)
	at com.intellij.codeInsight.documentation.DocumentationManager.a(DocumentationManager.java:720)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.util.Alarm$Request.run(Alarm.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:379)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:251)
	at lv.kid.vermut.intellij.yaml.reference.AnsibleVariableValuesDocumentationProvider.getQuickNavigateInfo(AnsibleVariableValuesDocumentationProvider.java:45)
	at lv.kid.vermut.intellij.yaml.reference.AnsibleVariableValuesDocumentationProvider.generateDoc(AnsibleVariableValuesDocumentationProvider.java:61)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:144)
	at com.intellij.codeInsight.documentation.DocumentationManager$DefaultDocumentationCollector.a(DocumentationManager.java:1149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1054)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:80)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:135)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:80)
	at com.intellij.codeInsight.documentation.QuickDocUtil.runInReadActionWithWriteActionPriorityWithRetries(QuickDocUtil.java:96)
	at com.intellij.codeInsight.documentation.DocumentationManager$DefaultDocumentationCollector.getDocumentation(DocumentationManager.java:1147)
	at com.intellij.codeInsight.documentation.DocumentationManager.a(DocumentationManager.java:720)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.util.Alarm$Request.run(Alarm.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by soar** [comment]
I have same problem.

**Comment by vermut** [comment]
This is because I go to internet to fetch fresh documentation each time Quick-Doc is accessed. Don't know what to do with the warning...

**Comment by lookatmypinky** [comment]
+1
WebStorm 2017.2 EAP
Build #WS-172.2465.2, built on May 23, 2017
WebStorm EAP User
Expiration date: June 22, 2017
JRE: 1.8.0_152-release-855-b1 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5
