### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by Vity01** [vermut/intellij-ansible#79]
Unfortunately I cannot provide company's yaml to public...
Plugin version 0.95

`null
java.lang.StackOverflowError
	at com.intellij.util.text.ImmutableText$CompositeNode.getChars(ImmutableText.java:547)
	at com.intellij.util.text.ImmutableText$CompositeNode.getChars(ImmutableText.java:550)
	at com.intellij.util.text.ImmutableText$CompositeNode.getChars(ImmutableText.java:550)
	at com.intellij.util.text.ImmutableText$CompositeNode.getChars(ImmutableText.java:547)
	at com.intellij.util.text.ImmutableText$CompositeNode.getChars(ImmutableText.java:550)
	at com.intellij.util.text.ImmutableText$CompositeNode.getChars(ImmutableText.java:550)
	at com.intellij.util.text.ImmutableText$CompositeNode.getChars(ImmutableText.java:547)
	at com.intellij.util.text.ImmutableText$CompositeNode.getChars(ImmutableText.java:550)
	at com.intellij.util.text.ImmutableText$CompositeNode.getChars(ImmutableText.java:550)
	at com.intellij.util.text.ImmutableText$CompositeNode.getChars(ImmutableText.java:547)
	at com.intellij.util.text.ImmutableText$CompositeNode.getChars(ImmutableText.java:547)
	at com.intellij.util.text.ImmutableText$CompositeNode.getChars(ImmutableText.java:550)
	at com.intellij.util.text.ImmutableText.getChars(ImmutableText.java:348)
	at com.intellij.util.text.CharArrayUtil.getChars(CharArrayUtil.java:68)
	at com.intellij.util.text.CharArrayUtil.fromSequence(CharArrayUtil.java:143)
	at com.intellij.util.text.CharSequenceSubSequence.toString(CharSequenceSubSequence.java:63)
	at com.intellij.lang.impl.PsiBuilderImpl.getTokenText(PsiBuilderImpl.java:807)
	at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseScalar(NeonParser.java:128)
	at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseScalar(NeonParser.java:185)
	at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseScalar(NeonParser.java:148)
	and so on... and so on....
	and so on... and so on....
	and so on... and so on....
	and so on... and so on....
	at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseScalar(NeonParser.java:185)
	at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseScalar(NeonParser.java:148)
	at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseScalar(NeonParser.java:185)
	at lv.kid.vermut.intellij.yaml.parser.NeonParser.parseScalar(NeonParser.java:148)
	at lv.kid.vermut.intellij.yaml.parser.NeonParser.parse(NeonParser.java:46)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:240)
	at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:157)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.findReparseableRoots(BlockSupportImpl.java:114)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:89)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:752)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$commitUnderProgress$4(DocumentCommitThread.java:533)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:556)
	at com.intellij.psi.impl.DocumentCommitThread.commitSynchronously(DocumentCommitThread.java:452)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$doCommit$0(PsiDocumentManagerBase.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1031)
	at com.intellij.psi.impl.PsiDocumentManagerBase.doCommit(PsiDocumentManagerBase.java:465)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitDocument(PsiDocumentManagerBase.java:313)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAllDocuments(PsiDocumentManagerBase.java:238)
	at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.writeExternal(DocumentFoldingInfo.java:208)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.writeFoldingState(CodeFoldingManagerImpl.java:350)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.writeState(PsiAwareTextEditorProvider.java:86)
	at com.intellij.openapi.fileEditor.impl.HistoryEntry.writeExternal(HistoryEntry.java:184)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.a(EditorsSplitters.java:230)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.a(EditorsSplitters.java:221)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.b(EditorsSplitters.java:201)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.writeExternal(EditorsSplitters.java:168)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getState(FileEditorManagerImpl.java:1482)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getState(FileEditorManagerImpl.java:107)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:227)
	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:159)
	at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:46)
	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:349)
	at com.intellij.ide.SaveAndSyncHandlerImpl.doSaveDocumentsAndProjectsAndApp(SaveAndSyncHandlerImpl.java:137)
	at com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:125)
	at com.intellij.ide.SaveAndSyncHandlerImpl$2.lambda$onFrameDeactivated$0(SaveAndSyncHandlerImpl.java:94)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.ide.SaveAndSyncHandlerImpl$2.onFrameDeactivated(SaveAndSyncHandlerImpl.java:92)
	at com.intellij.ide.FrameStateManagerImpl.a(FrameStateManagerImpl.java:84)
	at com.intellij.ide.FrameStateManagerImpl.access$500(FrameStateManagerImpl.java:32)
	at com.intellij.ide.FrameStateManagerImpl$2.lambda$applicationDeactivated$0(FrameStateManagerImpl.java:70)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by vermut** [comment]
Can't reproduce, sorry
