### ISSUE TITLE
Random error while using JetBrains PyCharm

### ISSUE THREAD

**Issue by taruntmr** [vermut/intellij-ansible#84]
null
java.lang.NullPointerException
	at lv.kid.vermut.intellij.yaml.reference.AnsibleFileReference.guessBestMatch(AnsibleFileReference.java:51)
	at lv.kid.vermut.intellij.yaml.reference.AnsibleFileReference.resolve(AnsibleFileReference.java:44)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.resolves(PsiMultiReference.java:52)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.lambda$static$0(PsiMultiReference.java:36)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.chooseReference(PsiMultiReference.java:72)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiMultiReference.getRangeInElement(PsiMultiReference.java:88)
	at com.intellij.psi.ReferenceRange.getRanges(ReferenceRange.java:38)
	at com.intellij.codeInsight.completion.CompletionData.getReferencePrefix(CompletionData.java:147)
	at com.intellij.codeInsight.completion.CompletionData.findPrefixStatic(CompletionData.java:176)
	at com.intellij.codeInsight.completion.CompletionData.findPrefixStatic(CompletionData.java:187)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.createResultSet(CompletionServiceImpl.java:91)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:82)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:116)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:812)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:797)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.a(CodeCompletionHandlerBase.java:293)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:181)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.a(CodeCompletionHandlerBase.java:290)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yura-shutkin** [comment]
Same error pycharm pro latest version (2018.1.3 181.4892.64)

[error.log](https://github.com/vermut/intellij-ansible/files/2059461/error.log)

**Comment by frbo42** [comment]
Got the same with 
IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Registry: 
Non-Bundled Plugins: 
YAML/Ansible support, 
org.asciidoctor.intellij.asciidoc, 
org.jetbrains.kotlin, 
com.intellij.plugins.html.instantEditing
